export const QUERY_KEYS = {
  USER: "user",
  GUESTS: "guests",
  STAFFS: "staffs",
  ROOMS: "rooms",
  ROOM_TYPES: "roomTypes",
  ROOM_DASHBOARD: "roomDashboard",
  RESERVATION_DASHBOARD: "reservationDashboard",
  RESERVATIONS: "reservations",
  CONFIRMED_RESERVATIONS: "confirmedReservations",
  FOOD_ITEMS: "foodItems",
  FOOD_ORDERS: "foodOrders",
  DASHBOARD_STATS: "dashboardStats",
  DISCOUNT_RATES: "discountRates",
  PAYMENTS: "payments",
};
